# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
# pod 'LinkedinSwift', '~> 1.4'
# platform :ios, '8.0'
# use_frameworks!
# pod 'ActiveLabel'
# */

target 'InYou' do

pod 'Google/SignIn'
pod 'Fabric'
pod 'Digits'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'AFNetworking', '~> 2.5'
use_frameworks!
pod 'performSelector-swift'
pod 'UIColor+FlatColors'
pod 'ReactiveUI'
pod 'PureLayout', '~> 3.0'

end
# post_install do |installer| `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
