//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.5
//
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:1bbbcd1b-7131-4800-84a4-773a6e7bf7df"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"77c3cfbc73614050bcbb0b96f2262f15"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"inyou-contentdelivery-mobilehub-1676967925"
// PUSH
#define AWS_SNS_PLATFORM_APPLICATION_ARN @"arn:aws:sns:us-east-1:550590175118:app/APNS_SANDBOX/inyou_MOBILEHUB_1676967925"
#define AWS_SNS_ALL_DEVICE_TOPIC_ARN @"arn:aws:sns:us-east-1:550590175118:inyou_alldevices_MOBILEHUB_1676967925"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"inyou-userfiles-mobilehub-1676967925"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub a6b08c22-5948-42d7-8ad3-c07e0f743638 aws-my-sample-app-ios-objc-v0.5"
